name: listenbrainz
description: A dart client for ListenBrainz.
version: 1.1.1
repository: https://github.com/wezencm/listenbrainz-dart-client
homepage: https://github.com/wezencm/listenbrainz-dart-client

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
